export async function seedTopic(prisma) {
   // 1. Fetch all existing categories to get their IDs
   const existingCategories = await prisma.category.findMany();

   // 2. Create a lookup map: { "Firewall": "uuid-123", "Networking": "uuid-456" }
   const categoryMap = {};
   existingCategories.forEach(cat => {
      categoryMap[cat.title] = cat.id;
   });

   // 3. Define your topics and tell the script which category title they belong to
   const topicsToSeed = [
      // Firewall Topics
      { title: "Disable", order: 1, categoryTitle: "Firewall" },
      { title: "Rules", order: 2, categoryTitle: "Firewall" },
      { title: "Network Profiling", order: 3, categoryTitle: "Firewall" },
      { title: "Network Sharing", order: 4, categoryTitle: "Firewall" },
      // ShortCuts Keys Topic
      { title: "Movement", order: 1, categoryTitle: "ShortCuts" },
      { title: "Naming Conventions", order: 2, categoryTitle: "ShortCuts" },
      { title: "Navigations", order: 3, categoryTitle: "ShortCuts" },
      { title: "VS Code", order: 4, categoryTitle: "ShortCuts" },
      { title: "Comment Styling", order: 5, categoryTitle: "ShortCuts" },
      // Window System Topic
      { title: "Operating System Doc File", order: 1, categoryTitle: "Windows" },
      // HTML Topics
      { title: "Syntax", order: 1, categoryTitle: "Basic" },
      { title: "Inline Vs Block", order: 2, categoryTitle: "Basic" },
      { title: "Comments", order: 3, categoryTitle: "Basic" },
      { title: "Title & FavIcon", order: 4, categoryTitle: "Basic" },
      { title: "Heading", order: 1, categoryTitle: "Headings and Paragraph" },
      { title: "Paragraph", order: 2, categoryTitle: "Headings and Paragraph" },
      { title: "Formetting", order: 1, categoryTitle: "Formatting" },
      { title: "Quotations", order: 2, categoryTitle: "Formatting" },
      { title: "Anchor", order: 1, categoryTitle: "Anchor & Link" },
      { title: "Link", order: 2, categoryTitle: "Anchor & Link" },
      { title: "Path", order: 1, categoryTitle: "Media" },
      { title: "Image", order: 2, categoryTitle: "Media" },
      { title: "Audio", order: 3, categoryTitle: "Media" },
      { title: "Video", order: 4, categoryTitle: "Media" },
      { title: "Table", order: 1, categoryTitle: "Table" },
      { title: "Unorder", order: 1, categoryTitle: "Lists & Dropdowns" },
      { title: "Order", order: 2, categoryTitle: "Lists & Dropdowns" },
      { title: "Description", order: 3, categoryTitle: "Lists & Dropdowns" },
      { title: "Dropdown", order: 4, categoryTitle: "Lists & Dropdowns" },
      { title: "Form", order: 1, categoryTitle: "Forms and Inputs" },
      { title: "Inputs", order: 2, categoryTitle: "Forms and Inputs" },
      { title: "Text Area", order: 3, categoryTitle: "Forms and Inputs" },
      { title: "Pre", order: 1, categoryTitle: "Misc" },
      { title: "Code", order: 2, categoryTitle: "Misc" },
      { title: "Samentic", order: 3, categoryTitle: "Misc" },
      // CSS Topics
      { title: "Syntax", order: 1, categoryTitle: "SyntaxAndStructure" },
      { title: "Inline", order: 2, categoryTitle: "SyntaxAndStructure" },
      { title: "Internal", order: 3, categoryTitle: "SyntaxAndStructure" },
      { title: "External", order: 4, categoryTitle: "SyntaxAndStructure" },
      { title: "Presidence", order: 5, categoryTitle: "SyntaxAndStructure" },
      { title: "Element", order: 1, categoryTitle: "Selectors" },
      { title: "Universal", order: 2, categoryTitle: "Selectors" },
      { title: "Class", order: 3, categoryTitle: "Selectors" },
      { title: "ID", order: 4, categoryTitle: "Selectors" },
      { title: "Color", order: 1, categoryTitle: "Background" },
      { title: "Image", order: 2, categoryTitle: "Background" },
      { title: "Repeat", order: 3, categoryTitle: "Background" },
      { title: "Size", order: 4, categoryTitle: "Background" },
      { title: "Position", order: 5, categoryTitle: "Background" },
      { title: "Attachment", order: 6, categoryTitle: "Background" },
      { title: "Shorthand", order: 7, categoryTitle: "Background" },
      { title: "Width", order: 1, categoryTitle: "BordersAndOutline" },
      { title: "Style", order: 2, categoryTitle: "BordersAndOutline" },
      { title: "Color", order: 3, categoryTitle: "BordersAndOutline" },
      { title: "ShortHand", order: 4, categoryTitle: "BordersAndOutline" },
      { title: "Border Radius", order: 5, categoryTitle: "BordersAndOutline" },
      { title: "Outline", order: 6, categoryTitle: "BordersAndOutline" },
      { title: "ShortHand", order: 7, categoryTitle: "BordersAndOutline" },
      { title: "Margin", order: 1, categoryTitle: "BoxModel" },
      { title: "Margin Collapse", order: 2, categoryTitle: "BoxModel" },
      { title: "Padding", order: 3, categoryTitle: "BoxModel" },
      { title: "Height(Min-h)", order: 4, categoryTitle: "BoxModel" },
      { title: "Width(Min-w)", order: 5, categoryTitle: "BoxModel" },
      { title: "Box Model", order: 6, categoryTitle: "BoxModel" },
      { title: "MeasurementUnits.php", order: 1, categoryTitle: "MeasurementUnits" },
      { title: "Colors", order: 1, categoryTitle: "ShadowAndGradient" },
      { title: "Colors Using Var", order: 2, categoryTitle: "ShadowAndGradient" },
      { title: "Gradient", order: 3, categoryTitle: "ShadowAndGradient" },

      // JavaScript Topics
      { title: "Basic Document Commands", order: 1, categoryTitle: "Basics JS" },
      { title: "HTML Inside JS", order: 2, categoryTitle: "Basics JS" },
      { title: "JS Inside HTML", order: 3, categoryTitle: "Basics JS" },
      { title: "JSON Understanding", order: 4, categoryTitle: "Basics JS" },

      { title: "Alert", order: 1, categoryTitle: "Alerts" },
      { title: "Prompt", order: 2, categoryTitle: "Alerts" },
      { title: "Confirm", order: 3, categoryTitle: "Alerts" },
      { title: "Log", order: 1, categoryTitle: "Console" },
      { title: "Warn", order: 2, categoryTitle: "Console" },
      { title: "Error", order: 3, categoryTitle: "Console" },
      { title: "Info", order: 4, categoryTitle: "Console" },
      { title: "Table", order: 5, categoryTitle: "Console" },
      { title: "Clear", order: 6, categoryTitle: "Console" },
      { title: "Time", order: 7, categoryTitle: "Console" },
      { title: "Time End", order: 8, categoryTitle: "Console" },
      { title: "Variable", order: 1, categoryTitle: "Variables" },
      { title: "Local Vs Global Variable", order: 2, categoryTitle: "Variables" },
      { title: "String", order: 1, categoryTitle: "String" },
      { title: "Length", order: 1, categoryTitle: "StringMethods" },
      { title: "LowerCase", order: 2, categoryTitle: "StringMethods" },
      { title: "UpperCase", order: 3, categoryTitle: "StringMethods" },
      { title: "Includes", order: 4, categoryTitle: "StringMethods" },
      { title: "Start With", order: 5, categoryTitle: "StringMethods" },
      { title: "End With", order: 6, categoryTitle: "StringMethods" },
      { title: "Search", order: 7, categoryTitle: "StringMethods" },
      { title: "Matches", order: 8, categoryTitle: "StringMethods" },
      { title: "Last Index Of", order: 9, categoryTitle: "StringMethods" },
      { title: "Replace", order: 10, categoryTitle: "StringMethods" },
      { title: "Trim", order: 11, categoryTitle: "StringMethods" },
      { title: "CharAt", order: 12, categoryTitle: "StringMethods" },
      { title: "CharCodeAt", order: 13, categoryTitle: "StringMethods" },
      { title: "FromCharCode", order: 14, categoryTitle: "StringMethods" },
      { title: "Concat", order: 15, categoryTitle: "StringMethods" },
      { title: "Split", order: 16, categoryTitle: "StringMethods" },
      { title: "Repeat", order: 17, categoryTitle: "StringMethods" },
      { title: "Slice", order: 18, categoryTitle: "StringMethods" },
      { title: "Splice", order: 19, categoryTitle: "StringMethods" },
      { title: "SubStr", order: 20, categoryTitle: "StringMethods" },
      { title: "SubString", order: 21, categoryTitle: "StringMethods" },
      { title: "ToString", order: 22, categoryTitle: "StringMethods" },
      { title: "Value Of", order: 23, categoryTitle: "StringMethods" },
      { title: "Number", order: 1, categoryTitle: "Number" },
      { title: "Number", order: 1, categoryTitle: "NumberMethods" },
      { title: "ParseInt", order: 2, categoryTitle: "NumberMethods" },
      { title: "ParseFloat", order: 3, categoryTitle: "NumberMethods" },
      { title: "IsFinite", order: 4, categoryTitle: "NumberMethods" },
      { title: "IsInteger", order: 5, categoryTitle: "NumberMethods" },
      { title: "ToFixed", order: 6, categoryTitle: "NumberMethods" },
      { title: "ToPrecision", order: 7, categoryTitle: "NumberMethods" },
      { title: "Boolean", order: 1, categoryTitle: "Boolean" },
      { title: "Abs", order: 1, categoryTitle: "BooleanMethods" },
      { title: "Cbrt", order: 2, categoryTitle: "BooleanMethods" },
      { title: "Ceil", order: 3, categoryTitle: "BooleanMethods" },
      { title: "Floot", order: 4, categoryTitle: "BooleanMethods" },
      { title: "Max", order: 5, categoryTitle: "BooleanMethods" },
      { title: "Min", order: 6, categoryTitle: "BooleanMethods" },
      { title: "Power", order: 7, categoryTitle: "BooleanMethods" },
      { title: "Random", order: 8, categoryTitle: "BooleanMethods" },
      { title: "Round", order: 9, categoryTitle: "BooleanMethods" },
      { title: "Sqrt", order: 10, categoryTitle: "BooleanMethods" },
      { title: "Trunc", order: 11, categoryTitle: "BooleanMethods" },
      { title: "Check ?", order: 12, categoryTitle: "BooleanMethods" },
      { title: "Acos", order: 13, categoryTitle: "BooleanMethods" },
      { title: "Asin", order: 14, categoryTitle: "BooleanMethods" },
      { title: "Atan", order: 15, categoryTitle: "BooleanMethods" },
      { title: "Cos", order: 16, categoryTitle: "BooleanMethods" },
      { title: "CosH", order: 17, categoryTitle: "BooleanMethods" },
      { title: "Exp", order: 18, categoryTitle: "BooleanMethods" },
      { title: "Hypot", order: 19, categoryTitle: "BooleanMethods" },
      { title: "Log", order: 20, categoryTitle: "BooleanMethods" },
      { title: "Sign", order: 21, categoryTitle: "BooleanMethods" },
      { title: "Sin", order: 22, categoryTitle: "BooleanMethods" },
      { title: "SinH", order: 23, categoryTitle: "BooleanMethods" },
      { title: "Tan", order: 24, categoryTitle: "BooleanMethods" },
      { title: "TanH", order: 25, categoryTitle: "BooleanMethods" },
      { title: "Null", order: 1, categoryTitle: "NullUndefined" },
      { title: "Undefined", order: 2, categoryTitle: "NullUndefined" },
      { title: "Array", order: 1, categoryTitle: "Arrays" },
      { title: "Multi Dimentional", order: 2, categoryTitle: "Arrays" },
      { title: "Object Inside Array", order: 3, categoryTitle: "Arrays" },
      { title: "Array Methods", order: 1, categoryTitle: "ArrayMethods" },
      { title: "Sort", order: 2, categoryTitle: "ArrayMethods" },
      { title: "Reverse", order: 3, categoryTitle: "ArrayMethods" },
      { title: "Pop", order: 4, categoryTitle: "ArrayMethods" },
      { title: "Push", order: 5, categoryTitle: "ArrayMethods" },
      { title: "Shift", order: 6, categoryTitle: "ArrayMethods" },
      { title: "Unshift", order: 7, categoryTitle: "ArrayMethods" },
      { title: "Concat", order: 8, categoryTitle: "ArrayMethods" },
      { title: "Join", order: 9, categoryTitle: "ArrayMethods" },
      { title: "Slice", order: 10, categoryTitle: "ArrayMethods" },
      { title: "Splice", order: 11, categoryTitle: "ArrayMethods" },
      { title: "IsArray", order: 12, categoryTitle: "ArrayMethods" },
      { title: "Index", order: 13, categoryTitle: "ArrayMethods" },
      { title: "Last Index", order: 14, categoryTitle: "ArrayMethods" },
      { title: "Entries", order: 15, categoryTitle: "ArrayMethods" },
      { title: "Every", order: 16, categoryTitle: "ArrayMethods" },
      { title: "Filter", order: 17, categoryTitle: "ArrayMethods" },
      { title: "Find", order: 18, categoryTitle: "ArrayMethods" },
      { title: "Find Index", order: 19, categoryTitle: "ArrayMethods" },
      { title: "Includes", order: 20, categoryTitle: "ArrayMethods" },
      { title: "Some", order: 21, categoryTitle: "ArrayMethods" },
      { title: "ToString", order: 22, categoryTitle: "ArrayMethods" },
      { title: "Value Of", order: 23, categoryTitle: "ArrayMethods" },
      { title: "Fill", order: 24, categoryTitle: "ArrayMethods" },
      { title: "For Each", order: 25, categoryTitle: "ArrayMethods" },
      { title: "Object", order: 1, categoryTitle: "Objects" },
      { title: "Array Inside Object", order: 2, categoryTitle: "Objects" },
      { title: "For In Loop", order: 1, categoryTitle: "ObjectMethods" },
      { title: "Map Method", order: 2, categoryTitle: "ObjectMethods" },
      { title: "Addition", order: 1, categoryTitle: "Arithematic Operators" },
      { title: "Subtraction", order: 2, categoryTitle: "Arithematic Operators" },
      { title: "Multiplication", order: 3, categoryTitle: "Arithematic Operators" },
      { title: "Division", order: 4, categoryTitle: "Arithematic Operators" },
      { title: "Modulus", order: 5, categoryTitle: "Arithematic Operators" },
      { title: "Exponentiation", order: 6, categoryTitle: "Arithematic Operators" },
      { title: "Increment", order: 7, categoryTitle: "Arithematic Operators" },
      { title: "Decrement", order: 8, categoryTitle: "Arithematic Operators" },
      { title: "Assignment", order: 1, categoryTitle: "Assignment Operators" },
      { title: "Addition & Assignment", order: 2, categoryTitle: "Assignment Operators" },
      { title: "Subtraction & Assignment", order: 3, categoryTitle: "Assignment Operators" },
      { title: "Multiplication & Assignment", order: 4, categoryTitle: "Assignment Operators" },
      { title: "Division & Assignment", order: 5, categoryTitle: "Assignment Operators" },
      { title: "Modulus & Assignment", order: 6, categoryTitle: "Assignment Operators" },
      { title: "Exponentiation & Assignment", order: 7, categoryTitle: "Assignment Operators" },
      { title: "Equal To", order: 1, categoryTitle: "Comparison Operators" },
      { title: "Strict Equal To", order: 2, categoryTitle: "Comparison Operators" },
      { title: "Not Equal To", order: 3, categoryTitle: "Comparison Operators" },
      { title: "Strict Not Equal To", order: 4, categoryTitle: "Comparison Operators" },
      { title: "Greater Than", order: 5, categoryTitle: "Comparison Operators" },
      { title: "Less Than", order: 6, categoryTitle: "Comparison Operators" },
      { title: "Greater Than Equal To", order: 7, categoryTitle: "Comparison Operators" },
      { title: "Less Than Equal To", order: 8, categoryTitle: "Comparison Operators" },
      { title: "And", order: 1, categoryTitle: "Logical Operators" },
      { title: "OR", order: 2, categoryTitle: "Logical Operators" },
      { title: "Not", order: 3, categoryTitle: "Logical Operators" },
      { title: "IF", order: 1, categoryTitle: "Conditionals" },
      { title: "IF Else", order: 2, categoryTitle: "Conditionals" },
      { title: "IF Else IF", order: 3, categoryTitle: "Conditionals" },
      { title: "Nested IF", order: 4, categoryTitle: "Conditionals" },
      { title: "Switch", order: 1, categoryTitle: "SwitchStatements" },
      { title: "Break", order: 2, categoryTitle: "SwitchStatements" },
      { title: "Continue", order: 3, categoryTitle: "SwitchStatements" },
      { title: "Default", order: 4, categoryTitle: "SwitchStatements" },
      { title: "Basic Function Syntax", order: 1, categoryTitle: "Functions JS" },
      { title: "Function with Return", order: 2, categoryTitle: "Functions JS" },
      { title: "Function With Param", order: 3, categoryTitle: "Functions JS" },
      { title: "Named Params", order: 4, categoryTitle: "Functions JS" },
      { title: "Default Params", order: 5, categoryTitle: "Functions JS" },
      { title: "Aero Functions", order: 6, categoryTitle: "Functions JS" },
      { title: "Variable Function", order: 7, categoryTitle: "Functions JS" },
      { title: "Date & Formats", order: 1, categoryTitle: "Date Methods" },
      { title: "Set Date", order: 2, categoryTitle: "Date Methods" },
      { title: "Set Month", order: 3, categoryTitle: "Date Methods" },
      { title: "Set Full Year", order: 4, categoryTitle: "Date Methods" },
      { title: "Set Hours", order: 5, categoryTitle: "Date Methods" },
      { title: "Set Minutes", order: 6, categoryTitle: "Date Methods" },
      { title: "Set Seconds", order: 7, categoryTitle: "Date Methods" },
      { title: "Set Miliseconds", order: 8, categoryTitle: "Date Methods" },
      { title: "Get Day", order: 9, categoryTitle: "Date Methods" },
      { title: "Get Time", order: 10, categoryTitle: "Date Methods" },
      { title: "Get Date", order: 11, categoryTitle: "Date Methods" },
      { title: "Get Month", order: 12, categoryTitle: "Date Methods" },
      { title: "Get Full Year", order: 13, categoryTitle: "Date Methods" },
      { title: "Get Hours", order: 14, categoryTitle: "Date Methods" },
      { title: "Get Minutes", order: 15, categoryTitle: "Date Methods" },
      { title: "Get Seconds", order: 16, categoryTitle: "Date Methods" },
      { title: "Get Miliseconds", order: 17, categoryTitle: "Date Methods" },
      { title: "While", order: 1, categoryTitle: "Loops JS" },
      { title: "Do While", order: 2, categoryTitle: "Loops JS" },
      { title: "For", order: 3, categoryTitle: "Loops JS" },
      { title: "Break", order: 4, categoryTitle: "Loops JS" },
      { title: "Continue", order: 5, categoryTitle: "Loops JS" },
      { title: "Nested Loop", order: 6, categoryTitle: "Loops JS" },
      { title: "Ex Even", order: 7, categoryTitle: "Loops JS" },
      { title: "Ex Odd", order: 8, categoryTitle: "Loops JS" },
      { title: "Ex SNO", order: 9, categoryTitle: "Loops JS" },
      { title: "On Click", order: 1, categoryTitle: "BasicEvents" },
      { title: "On Double Click", order: 2, categoryTitle: "BasicEvents" },
      { title: "On Context Menu", order: 3, categoryTitle: "BasicEvents" },
      { title: "On Mouse Enter", order: 4, categoryTitle: "BasicEvents" },
      { title: "On Mouse Over", order: 5, categoryTitle: "BasicEvents" },
      { title: "On Mouse Out", order: 6, categoryTitle: "BasicEvents" },
      { title: "On Mouse Up", order: 7, categoryTitle: "BasicEvents" },
      { title: "On Mouse Down", order: 8, categoryTitle: "BasicEvents" },
      { title: "On Key Press", order: 9, categoryTitle: "BasicEvents" },
      { title: "On Key Down", order: 10, categoryTitle: "BasicEvents" },
      { title: "On Key Up", order: 11, categoryTitle: "BasicEvents" },
      { title: "On Load", order: 12, categoryTitle: "BasicEvents" },
      { title: "On Resize", order: 13, categoryTitle: "BasicEvents" },
      { title: "On Scroll", order: 14, categoryTitle: "BasicEvents" },
      { title: "On Focus", order: 1, categoryTitle: "FormEvents" },
      { title: "On Blur", order: 2, categoryTitle: "FormEvents" },
      { title: "On Input", order: 3, categoryTitle: "FormEvents" },
      { title: "On Change", order: 4, categoryTitle: "FormEvents" },
      { title: "On Select", order: 5, categoryTitle: "FormEvents" },
      { title: "On Submit", order: 6, categoryTitle: "FormEvents" },
      { title: "On Invalid", order: 7, categoryTitle: "FormEvents" },
      { title: "Set Interval", order: 1, categoryTitle: "Interval" },
      { title: "Clear Interval", order: 2, categoryTitle: "Interval" },
      { title: "Set Timeout", order: 1, categoryTitle: "TimeOut" },
      { title: "Clear Timeout", order: 2, categoryTitle: "TimeOut" },
      { title: "Ctrl Key", order: 1, categoryTitle: "Keys" },
      { title: "Alt Key", order: 2, categoryTitle: "Keys" },
      { title: "Shift Key", order: 3, categoryTitle: "Keys" },
      { title: "Meta Key", order: 4, categoryTitle: "Keys" },
      { title: "Mouse Key", order: 5, categoryTitle: "Keys" },
      { title: "Custom Key Code", order: 6, categoryTitle: "Keys" },
      { title: "On Cut", order: 1, categoryTitle: "ClipBoard" },
      { title: "On Copy", order: 2, categoryTitle: "ClipBoard" },
      { title: "On Paste", order: 3, categoryTitle: "ClipBoard" },
      { title: "Online", order: 1, categoryTitle: "Internet" },
      { title: "Offline", order: 2, categoryTitle: "Internet" },
      { title: "Console Navigator", order: 3, categoryTitle: "Internet" },
      { title: "Document", order: 1, categoryTitle: "BasicDocumentCommands" },
      { title: "Document All", order: 2, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Element", order: 3, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Head", order: 4, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Body", order: 5, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Image", order: 6, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Anchor", order: 7, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Links", order: 8, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Forms", order: 9, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Doctype", order: 10, categoryTitle: "BasicDocumentCommands" },
      { title: "Document URL", order: 11, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Base URI", order: 12, categoryTitle: "BasicDocumentCommands" },
      { title: "Document Domain", order: 13, categoryTitle: "BasicDocumentCommands" },
      { title: "Get Element By ID", order: 1, categoryTitle: "ElementSelectors" },
      { title: "Get Element By Class", order: 2, categoryTitle: "ElementSelectors" },
      { title: "get Element By TagName", order: 3, categoryTitle: "ElementSelectors" },
      { title: "Query Selector", order: 1, categoryTitle: "QuerySelectors" },
      { title: "Query Selector All", order: 2, categoryTitle: "QuerySelectors" },
      { title: "Inner Text", order: 1, categoryTitle: "InnerTextAndHTML" },
      { title: "Inner HTML", order: 2, categoryTitle: "InnerTextAndHTML" },
      { title: "Attributes", order: 1, categoryTitle: "Attributes" },
      { title: "Get Attribute", order: 2, categoryTitle: "Attributes" },
      { title: "Set Attribute", order: 3, categoryTitle: "Attributes" },
      { title: "Remove Attribute", order: 4, categoryTitle: "Attributes" },
      { title: "Get Attribute Node", order: 5, categoryTitle: "Attributes" },
      { title: "Has Attribute", order: 6, categoryTitle: "Attributes" },
      { title: "Style", order: 1, categoryTitle: "Styling" },
      { title: "Class Name", order: 2, categoryTitle: "Styling" },
      { title: "Class List", order: 1, categoryTitle: "ClassList" },
      { title: "Add", order: 2, categoryTitle: "ClassList" },
      { title: "Remove", order: 3, categoryTitle: "ClassList" },
      { title: "Toggle", order: 4, categoryTitle: "ClassList" },
      { title: "Contains", order: 5, categoryTitle: "ClassList" },
      { title: "Item", order: 6, categoryTitle: "ClassList" },
      { title: "Length", order: 7, categoryTitle: "ClassList" },
      { title: "Parent Element", order: 1, categoryTitle: "TraversingMethods" },
      { title: "Parent Node", order: 2, categoryTitle: "TraversingMethods" },
      { title: "Children", order: 3, categoryTitle: "TraversingMethods" },
      { title: "Child Nodes", order: 4, categoryTitle: "TraversingMethods" },
      { title: "First Child", order: 5, categoryTitle: "TraversingMethods" },
      { title: "Last Child", order: 6, categoryTitle: "TraversingMethods" },
      { title: "First Element ID", order: 7, categoryTitle: "TraversingMethods" },
      { title: "Last Element ID", order: 8, categoryTitle: "TraversingMethods" },
      { title: "Next Sibling", order: 9, categoryTitle: "TraversingMethods" },
      { title: "Previous Sibling", order: 10, categoryTitle: "TraversingMethods" },
      { title: "Next Element Sibling", order: 11, categoryTitle: "TraversingMethods" },
      { title: "Previous Element Sibling", order: 12, categoryTitle: "TraversingMethods" },
      { title: "Create Element", order: 1, categoryTitle: "CreateMethods" },
      { title: "Create Text Node", order: 2, categoryTitle: "CreateMethods" },
      { title: "Create Comment", order: 3, categoryTitle: "CreateMethods" },
      { title: "Append Child", order: 1, categoryTitle: "AppendMethods" },
      { title: "Insert Before", order: 2, categoryTitle: "AppendMethods" },
      { title: "Insert Adjacent Element", order: 1, categoryTitle: "InsertAdjacentMethods" },
      { title: "Insert Adjacent HTML", order: 2, categoryTitle: "InsertAdjacentMethods" },
      { title: "Insert Adjacent Text", order: 3, categoryTitle: "InsertAdjacentMethods" },
      { title: "Replace Child", order: 1, categoryTitle: "ChildMethod" },
      { title: "Remove Child", order: 2, categoryTitle: "ChildMethod" },
      { title: "Has Attribute", order: 1, categoryTitle: "HasMethods" },
      { title: "Has Child Node", order: 2, categoryTitle: "HasMethods" },
      { title: "Clone Node", order: 1, categoryTitle: "MiscMethods" },
      { title: "Is Equal Node", order: 2, categoryTitle: "MiscMethods" },
      { title: "Contains", order: 3, categoryTitle: "MiscMethods" },
      { title: "Inner Width", order: 1, categoryTitle: "WindowDimentions" },
      { title: "Outer Width", order: 2, categoryTitle: "WindowDimentions" },
      { title: "Inner Height", order: 3, categoryTitle: "WindowDimentions" },
      { title: "Outer Height", order: 4, categoryTitle: "WindowDimentions" },
      { title: "Open", order: 1, categoryTitle: "WindowControls" },
      { title: "Close", order: 2, categoryTitle: "WindowControls" },
      { title: "Focus", order: 3, categoryTitle: "WindowControls" },
      { title: "Move By", order: 1, categoryTitle: "WindowMove" },
      { title: "Move To", order: 2, categoryTitle: "WindowMove" },
      { title: "Resize By", order: 1, categoryTitle: "WindowResize" },
      { title: "Resize To", order: 2, categoryTitle: "WindowResize" },
      { title: "Scroll By", order: 1, categoryTitle: "WindowScroll" },
      { title: "Scroll To", order: 2, categoryTitle: "WindowScroll" },
      { title: "Location", order: 1, categoryTitle: "LocationAndHistory" },
      { title: "History", order: 2, categoryTitle: "LocationAndHistory" },
      { title: "Page X", order: 1, categoryTitle: "CursorCoordinates" },
      { title: "Page Y", order: 2, categoryTitle: "CursorCoordinates" },
      { title: "Screen X", order: 3, categoryTitle: "CursorCoordinates" },
      { title: "Screen Y", order: 4, categoryTitle: "CursorCoordinates" },
      { title: "OffSet X", order: 5, categoryTitle: "CursorCoordinates" },
      { title: "OffSet Y", order: 6, categoryTitle: "CursorCoordinates" },
      { title: "Client X", order: 7, categoryTitle: "CursorCoordinates" },
      { title: "Client Y", order: 8, categoryTitle: "CursorCoordinates" },
      { title: "Page X OffSet", order: 1, categoryTitle: "ScrollAmounts" },
      { title: "Page Y OffSet", order: 2, categoryTitle: "ScrollAmounts" },
      { title: "Scroll Top", order: 3, categoryTitle: "ScrollAmounts" },
      { title: "Scroll Left", order: 4, categoryTitle: "ScrollAmounts" },
      { title: "Scroll Set Top", order: 5, categoryTitle: "ScrollAmounts" },
      { title: "Scroll Set Left", order: 6, categoryTitle: "ScrollAmounts" },
      { title: "Scroll Width", order: 7, categoryTitle: "ScrollAmounts" },
      { title: "Scroll Height", order: 8, categoryTitle: "ScrollAmounts" },
      { title: "OffSet Width", order: 9, categoryTitle: "ScrollAmounts" },
      { title: "OffSet Height", order: 10, categoryTitle: "ScrollAmounts" },
      { title: "Client Width", order: 11, categoryTitle: "ScrollAmounts" },
      { title: "Client Height", order: 12, categoryTitle: "ScrollAmounts" },
      // PHP Proceedural Topics
      { title: "Comments", order: 1, categoryTitle: "Basics" },
      { title: "Basic Syntax", order: 2, categoryTitle: "Basics" },
      { title: "Echo Print", order: 3, categoryTitle: "Basics" },
      { title: "Here Doc", order: 4, categoryTitle: "Basics" },
      { title: "Now Doc", order: 5, categoryTitle: "Basics" },
      { title: "Expression", order: 6, categoryTitle: "Basics" },
      { title: "PHP Short Hand", order: 7, categoryTitle: "Basics" },
      { title: "HTML In PHP", order: 8, categoryTitle: "Basics" },
      { title: "Comments & DocBlock", order: 9, categoryTitle: "Basics" },
      { title: "String", order: 1, categoryTitle: "StringTypes" },
      { title: "Single Vs Double Quote Strings", order: 2, categoryTitle: "StringTypes" },
      { title: "Appostrophy", order: 3, categoryTitle: "StringTypes" },
      { title: "Accessing Char", order: 4, categoryTitle: "StringTypes" },
      { title: "Concatination", order: 5, categoryTitle: "StringTypes" },
      { title: "Length", order: 6, categoryTitle: "StringTypes" },
      { title: "Case Changing", order: 7, categoryTitle: "StringTypes" },
      { title: "Title Case", order: 8, categoryTitle: "StringTypes" },
      { title: "Replace", order: 9, categoryTitle: "StringTypes" },
      { title: "Trim", order: 10, categoryTitle: "StringTypes" },
      { title: "Padding", order: 11, categoryTitle: "StringTypes" },
      { title: "Position", order: 12, categoryTitle: "StringTypes" },
      { title: "Extract SubString", order: 13, categoryTitle: "StringTypes" },
      { title: "Comparing String", order: 14, categoryTitle: "StringTypes" },
      { title: "Formatting", order: 15, categoryTitle: "StringTypes" },
      { title: "Persing String", order: 16, categoryTitle: "StringTypes" },
      { title: "Join Array Element", order: 17, categoryTitle: "StringTypes" },
      { title: "Repeating String", order: 18, categoryTitle: "StringTypes" },
      { title: "Random", order: 19, categoryTitle: "StringTypes" },
      { title: "Cx SubString", order: 20, categoryTitle: "StringTypes" },
      { title: "Cx StrStart With SubStr", order: 21, categoryTitle: "StringTypes" },
      { title: "String To Array", order: 22, categoryTitle: "StringTypes" },
      { title: "String To Array (Lines)", order: 23, categoryTitle: "StringTypes" },
      { title: "String To Array (Words)", order: 24, categoryTitle: "StringTypes" },
      { title: "Replace Index Num", order: 25, categoryTitle: "StringTypes" },
      { title: "Replace Index Num NA", order: 26, categoryTitle: "StringTypes" },
      { title: "Integer", order: 1, categoryTitle: "IntegerTypes&Methods" },
      { title: "Hexa Num", order: 2, categoryTitle: "IntegerTypes&Methods" },
      { title: "Octa Num", order: 3, categoryTitle: "IntegerTypes&Methods" },
      { title: "Binary Num", order: 4, categoryTitle: "IntegerTypes&Methods" },
      { title: "Constant (INT-MAX)", order: 5, categoryTitle: "IntegerTypes&Methods" },
      { title: "Constant (INT-MIN)", order: 6, categoryTitle: "IntegerTypes&Methods" },
      { title: "IntSize", order: 7, categoryTitle: "IntegerTypes&Methods" },
      { title: "Ex-1+INT_Max", order: 8, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast Str as Int", order: 9, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast AlphaNum as Int", order: 10, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast Float As Int", order: 11, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast FloatStr As Int", order: 12, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast Boolean As Int(True)", order: 13, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast Boolean As Int(False)", order: 14, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast Null As Int", order: 15, categoryTitle: "IntegerTypes&Methods" },
      { title: "Cast Underscore As Int", order: 16, categoryTitle: "IntegerTypes&Methods" },
      { title: "Float Or Double", order: 1, categoryTitle: "FloatTypes&Methods" },
      { title: "UnderScor Float", order: 2, categoryTitle: "FloatTypes&Methods" },
      { title: "E-Float", order: 3, categoryTitle: "FloatTypes&Methods" },
      { title: "Underscore E-Float", order: 4, categoryTitle: "FloatTypes&Methods" },
      { title: "Underscore E3-Float", order: 5, categoryTitle: "FloatTypes&Methods" },
      { title: "Const(Float-Max)", order: 6, categoryTitle: "FloatTypes&Methods" },
      { title: "Const(Float-Min)", order: 7, categoryTitle: "FloatTypes&Methods" },
      { title: "Binary Float", order: 8, categoryTitle: "FloatTypes&Methods" },
      { title: "Binary Float Ceil", order: 9, categoryTitle: "FloatTypes&Methods" },
      { title: "Binary Float Ceil2", order: 10, categoryTitle: "FloatTypes&Methods" },
      { title: "Binary Float Never Trust", order: 11, categoryTitle: "FloatTypes&Methods" },
      { title: "Binary Float NAN", order: 12, categoryTitle: "FloatTypes&Methods" },
      { title: "Binary Float INF", order: 13, categoryTitle: "FloatTypes&Methods" },
      { title: "Cx NAN Or INF", order: 14, categoryTitle: "FloatTypes&Methods" },
      { title: "Cast Float True", order: 15, categoryTitle: "FloatTypes&Methods" },
      { title: "Cast Float String", order: 16, categoryTitle: "FloatTypes&Methods" },
      { title: "Boolean", order: 1, categoryTitle: "BooleanTypes&Methods" },
      { title: "Cx-Boolean", order: 2, categoryTitle: "BooleanTypes&Methods" },
      { title: "Cx-Int", order: 3, categoryTitle: "BooleanTypes&Methods" },
      { title: "Cx-Floats", order: 4, categoryTitle: "BooleanTypes&Methods" },
      { title: "Cx-String", order: 5, categoryTitle: "BooleanTypes&Methods" },
      { title: "Cx-Blank Array", order: 6, categoryTitle: "BooleanTypes&Methods" },
      { title: "Cx-Null", order: 7, categoryTitle: "BooleanTypes&Methods" },
      { title: "Array", order: 1, categoryTitle: "ArrayTypes&Methods" },
      { title: "Create Array", order: 2, categoryTitle: "ArrayTypes&Methods" },
      { title: "Create Array Fn", order: 3, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Index", order: 4, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Index Fn", order: 5, categoryTitle: "ArrayTypes&Methods" },
      { title: "Custome Index", order: 6, categoryTitle: "ArrayTypes&Methods" },
      { title: "Accessing Index", order: 7, categoryTitle: "ArrayTypes&Methods" },
      { title: "Accessing Last Index", order: 8, categoryTitle: "ArrayTypes&Methods" },
      { title: "Cx-Index Exists", order: 9, categoryTitle: "ArrayTypes&Methods" },
      { title: "In Array", order: 10, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Search", order: 11, categoryTitle: "ArrayTypes&Methods" },
      { title: "Add Element", order: 12, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Push", order: 13, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Unshift", order: 14, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Pop", order: 15, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Shift", order: 16, categoryTitle: "ArrayTypes&Methods" },
      { title: "Unset", order: 17, categoryTitle: "ArrayTypes&Methods" },
      { title: "Change Value Of Index", order: 18, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Splice", order: 19, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Replace", order: 20, categoryTitle: "ArrayTypes&Methods" },
      { title: "Print Array", order: 21, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Count", order: 22, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Size", order: 23, categoryTitle: "ArrayTypes&Methods" },
      { title: "Add New Index & Value", order: 24, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Merge", order: 25, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Combine", order: 26, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Fill Keys", order: 27, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Fill", order: 28, categoryTitle: "ArrayTypes&Methods" },
      { title: "Multi Dimentional Array", order: 29, categoryTitle: "ArrayTypes&Methods" },
      { title: "Accessing Multi Dimentional Array", order: 30, categoryTitle: "ArrayTypes&Methods" },
      { title: "Accessign Duplicate Index", order: 31, categoryTitle: "ArrayTypes&Methods" },
      { title: "Same Index Diff Data Type Err", order: 32, categoryTitle: "ArrayTypes&Methods" },
      { title: "Index Arrangement", order: 33, categoryTitle: "ArrayTypes&Methods" },
      { title: "Isset-Array Key Exists", order: 34, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Functions", order: 35, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Chunks", order: 36, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Filter", order: 37, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Keys", order: 38, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Values", order: 39, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Pointer", order: 40, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Map", order: 41, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Merge", order: 42, categoryTitle: "ArrayTypes&Methods" },
      { title: "Array Reduce", order: 43, categoryTitle: "ArrayTypes&Methods" },
      { title: "Null ", order: 1, categoryTitle: "Null" },
      { title: "Cx-IsNull", order: 2, categoryTitle: "Null" },
      { title: "Cx-IsSet", order: 3, categoryTitle: "Null" },
      { title: "Cx-Empty", order: 4, categoryTitle: "Null" },
      { title: "Cx-Undefined", order: 5, categoryTitle: "Null" },
      { title: "Unset", order: 6, categoryTitle: "Null" },
      { title: "Cast Str As Null", order: 7, categoryTitle: "Null" },
      { title: "Cast Int As Null", order: 8, categoryTitle: "Null" },
      { title: "Cast Float As Null", order: 9, categoryTitle: "Null" },
      { title: "Cast Boolean As Null", order: 10, categoryTitle: "Null" },
      { title: "Cast Array As Null", order: 11, categoryTitle: "Null" },
      { title: "Resource", order: 1, categoryTitle: "Resource" },
      { title: "Interesting Types Handeling", order: 2, categoryTitle: "Resource" },
      { title: "Variable By Value", order: 1, categoryTitle: "Variable&Scopes" },
      { title: "Variable By Reference", order: 2, categoryTitle: "Variable&Scopes" },
      { title: "Define Const", order: 3, categoryTitle: "Variable&Scopes" },
      { title: "CONST", order: 4, categoryTitle: "Variable&Scopes" },
      { title: "Variable Variable", order: 5, categoryTitle: "Variable&Scopes" },
      { title: "Variable Scopes", order: 6, categoryTitle: "Variable&Scopes" },
      { title: "Static Variable", order: 7, categoryTitle: "Variable&Scopes" },
      { title: "Basic Arithematic Operatior", order: 1, categoryTitle: "ArithematicOperators" },
      { title: "Addition", order: 2, categoryTitle: "ArithematicOperators" },
      { title: "Subtraction", order: 3, categoryTitle: "ArithematicOperators" },
      { title: "Multiplication", order: 4, categoryTitle: "ArithematicOperators" },
      { title: "Division ", order: 5, categoryTitle: "ArithematicOperators" },
      { title: "Modulus", order: 6, categoryTitle: "ArithematicOperators" },
      { title: "Exponentiation", order: 7, categoryTitle: "ArithematicOperators" },
      { title: "Basic Assignment Operator", order: 1, categoryTitle: "AssignmentOperators" },
      { title: "Assignment", order: 2, categoryTitle: "AssignmentOperators" },
      { title: "Addition & Assignment", order: 3, categoryTitle: "AssignmentOperators" },
      { title: "Subtraction & Assignment", order: 4, categoryTitle: "AssignmentOperators" },
      { title: "Multiplication & Assignment", order: 5, categoryTitle: "AssignmentOperators" },
      { title: "Division & Assignment", order: 6, categoryTitle: "AssignmentOperators" },
      { title: "Exponentiation & Assignment", order: 7, categoryTitle: "AssignmentOperators" },
      { title: "Concatenate & Assign", order: 8, categoryTitle: "AssignmentOperators" },
      { title: "Concatenation Operator", order: 1, categoryTitle: "StringOperators" },
      { title: "Concatenate & Assign", order: 2, categoryTitle: "StringOperators" },
      { title: "Equal", order: 1, categoryTitle: "ComparisonOperators" },
      { title: "Identical", order: 2, categoryTitle: "ComparisonOperators" },
      { title: "Not Equal ", order: 3, categoryTitle: "ComparisonOperators" },
      { title: "Not Identical", order: 4, categoryTitle: "ComparisonOperators" },
      { title: "Grater Than", order: 5, categoryTitle: "ComparisonOperators" },
      { title: "Less Than", order: 6, categoryTitle: "ComparisonOperators" },
      { title: "Grater Than Equal To", order: 7, categoryTitle: "ComparisonOperators" },
      { title: "Less Than Equal To", order: 8, categoryTitle: "ComparisonOperators" },
      { title: "Space Ship Operator", order: 9, categoryTitle: "ComparisonOperators" },
      { title: "Turnary Operator", order: 1, categoryTitle: "TurnaryOperator" },
      { title: "Null Coalesing", order: 1, categoryTitle: "NullCoalescingOperator" },
      { title: "Error Control Operator", order: 1, categoryTitle: "ErrorControlOperator" },
      { title: "Pre Increment", order: 1, categoryTitle: "IncrementDecrementOperator" },
      { title: "Pre Decrement", order: 2, categoryTitle: "IncrementDecrementOperator" },
      { title: "Post Increment", order: 3, categoryTitle: "IncrementDecrementOperator" },
      { title: "Post Decrement", order: 4, categoryTitle: "IncrementDecrementOperator" },
      { title: "Increment String", order: 5, categoryTitle: "IncrementDecrementOperator" },
      { title: "Decrement String", order: 6, categoryTitle: "IncrementDecrementOperator" },
      { title: "Increment Alphabet", order: 7, categoryTitle: "IncrementDecrementOperator" },
      { title: "Decrement Alphabet", order: 8, categoryTitle: "IncrementDecrementOperator" },
      { title: "AND", order: 1, categoryTitle: "LogicalOperator" },
      { title: "OR", order: 2, categoryTitle: "LogicalOperator" },
      { title: "NOT", order: 3, categoryTitle: "LogicalOperator" },
      { title: "And", order: 4, categoryTitle: "LogicalOperator" },
      { title: "Or", order: 5, categoryTitle: "LogicalOperator" },
      { title: "Xor", order: 6, categoryTitle: "LogicalOperator" },
      { title: "Short Circuit Evaluation", order: 1, categoryTitle: "ShortCircuitOperator" },
      { title: "And", order: 1, categoryTitle: "BitWiseOperator" },
      { title: "Or", order: 2, categoryTitle: "BitWiseOperator" },
      { title: "Xor", order: 3, categoryTitle: "BitWiseOperator" },
      { title: "Not", order: 4, categoryTitle: "BitWiseOperator" },
      { title: "Shift Left", order: 5, categoryTitle: "BitWiseOperator" },
      { title: "Shift Right", order: 6, categoryTitle: "BitWiseOperator" },
      { title: "Union", order: 1, categoryTitle: "ArrayOperators" },
      { title: "Equal", order: 2, categoryTitle: "ArrayOperators" },
      { title: "Not Equal ", order: 3, categoryTitle: "ArrayOperators" },
      { title: "Identical", order: 4, categoryTitle: "ArrayOperators" },
      { title: "Not Identical", order: 5, categoryTitle: "ArrayOperators" },
      { title: "Execution", order: 1, categoryTitle: "ExecutionOperator" },
      { title: "InstanceOf", order: 1, categoryTitle: "TypeOperator" },
      { title: "Null Safe", order: 1, categoryTitle: "NullSafeOperator" },
      { title: "Spaceship", order: 1, categoryTitle: "SpaceshipOperator" },
      { title: "Presidence", order: 1, categoryTitle: "Presidence&Associativity" },
      { title: "Associativity", order: 2, categoryTitle: "Presidence&Associativity" },
      { title: "Control Structure", order: 1, categoryTitle: "ControlStructure" },
      { title: "Switch", order: 2, categoryTitle: "ControlStructure" },
      { title: "Match", order: 3, categoryTitle: "ControlStructure" },
      { title: "Echo Print Function", order: 1, categoryTitle: "Functions" },
      { title: "Null Return Function", order: 2, categoryTitle: "Functions" },
      { title: "Fn Inside Conditionals", order: 3, categoryTitle: "Functions" },
      { title: "Fn Inside Function", order: 4, categoryTitle: "Functions" },
      { title: "Return Types Painting", order: 5, categoryTitle: "Functions" },
      { title: "Params Arguments", order: 6, categoryTitle: "Functions" },
      { title: "Variable Scopes", order: 7, categoryTitle: "Functions" },
      { title: "Static Variable", order: 8, categoryTitle: "Functions" },
      { title: "Variable Anonomous Arrow Fn", order: 9, categoryTitle: "Functions" },
      { title: "Callback Fn", order: 10, categoryTitle: "Functions" },
      { title: "Date & Methods", order: 1, categoryTitle: "Date" },
      { title: "Date Formates", order: 2, categoryTitle: "Date" },
      { title: "While", order: 1, categoryTitle: "Loops" },
      { title: "Do While", order: 2, categoryTitle: "Loops" },
      { title: "For Loop", order: 3, categoryTitle: "Loops" },
      { title: "For Each", order: 4, categoryTitle: "Loops" },
      { title: "For Each", order: 5, categoryTitle: "Loops" },
      { title: "For Each Array To Str", order: 6, categoryTitle: "Loops" },
      { title: "Declare Encoding", order: 1, categoryTitle: "Declare" },
      { title: "Declare Statement", order: 2, categoryTitle: "Declare" },
      { title: "Declare Strict Types", order: 3, categoryTitle: "Declare" },
      { title: "Declare Tick", order: 4, categoryTitle: "Declare" },
      { title: "Return Statement", order: 1, categoryTitle: "Return&Yield" },
      { title: "Yield Include", order: 2, categoryTitle: "Return&Yield" },
      { title: "Include", order: 1, categoryTitle: "Include&Require" },
      { title: "Require", order: 2, categoryTitle: "Include&Require" },

   ];

   // 4. Loop through topics and create them
   for (const t of topicsToSeed) {
      const targetCategoryId = categoryMap[t.categoryTitle];

      if (!targetCategoryId) {
         console.error(`❌ Category "${t.categoryTitle}" not found for topic "${t.title}"`);
         continue;
      }

      // Check if topic already exists to prevent duplicates
      const existingTopic = await prisma.topic.findFirst({
         where: {
            title: t.title,
            categoryId: targetCategoryId
         }
      });

      if (!existingTopic) {
         await prisma.topic.create({
            data: {
               title: t.title,
               order: t.order,
               categoryId: targetCategoryId // This is attached automatically now
            }
         });
      }
   }

   console.log("✅ Topics seeded and attached to categories");
}